# Generated by Django 3.1 on 2020-12-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('personal_image', models.ImageField(default='default.jpg', upload_to='applicant_pics')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone_number', models.FloatField(verbose_name='Phone Number')),
                ('a_phone_number', models.FloatField(blank=True, null=True, verbose_name='Phone Number (optional)')),
                ('national_id', models.FloatField(unique=True, verbose_name='National Id')),
                ('available', models.BooleanField(default=False, verbose_name='Available for video interview')),
                ('college', models.CharField(max_length=255, verbose_name='College')),
                ('year', models.IntegerField(verbose_name='Academic Year')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255, verbose_name='Gender')),
                ('why', models.TextField(verbose_name='Why Do you want to join us?')),
                ('how', models.TextField(verbose_name='How did you know about us')),
                ('what', models.TextField(verbose_name='What Skills do you have besides PR skills?')),
                ('position', models.CharField(choices=[('PR', 'PR')], default='PR', max_length=255, verbose_name='Position')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
