# Generated by Django 3.1 on 2020-09-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date_of_birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_publisher',
            field=models.BooleanField(default=False, verbose_name='is_publisher'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=True, verbose_name='is_student'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.FloatField(unique=True, verbose_name='national_id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.FloatField(verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=255, verbose_name='year'),
        ),
    ]
