# Generated by Django 3.1 on 2020-12-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201209_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='personal_image',
            field=models.ImageField(upload_to='applicant_pics'),
        ),
    ]
