# Generated by Django 3.1.4 on 2021-01-03 23:28

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201223_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='notes1',
            field=models.TextField(blank=True, null=True, verbose_name='The first interviewer notes'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='notes2',
            field=models.TextField(blank=True, null=True, verbose_name='The second interviewer notes'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rating1',
            field=models.IntegerField(blank=True, null=True, verbose_name='The first interviewer notes (/10)'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rating2',
            field=models.IntegerField(blank=True, null=True, verbose_name='The second interviewer notes (/10)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=users.models.get_upload_path),
        ),
    ]
