# Generated by Django 3.1.4 on 2021-02-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210209_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='position',
            field=models.CharField(choices=[('PR', 'PR'), ('Customer Service', 'Customer Service'), ('technical support agent', 'technical support agent')], max_length=255, verbose_name='Position'),
        ),
    ]
