# Generated by Django 3.2.3 on 2021-06-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210211_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='position',
            field=models.CharField(choices=[('PR', 'PR'), ('Customer Service', 'Customer Service'), ('Graphic Designer', 'Graphic Designer'), ('technical support agent', 'technical support agent')], max_length=255, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='what',
            field=models.TextField(verbose_name='What Skills do you have besides the requirements?'),
        ),
    ]
