# Generated by Django 3.2.3 on 2021-07-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210630_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
    ]
