# Generated by Django 3.1.4 on 2021-01-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mrehaburl'),
    ]

    operations = [
        migrations.CreateModel(
            name='HerrMURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(default='http://al3wn.com/', max_length=512)),
            ],
        ),
    ]
