# Generated by Django 3.1.4 on 2021-01-24 23:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210114_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='BassemURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('up', 'up'), ('perfect', 'perfect')], max_length=255, verbose_name='Kind')),
                ('link', models.URLField(default='http://al3wn.com/', max_length=512)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
