# Generated by Django 3.1.4 on 2021-01-26 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bassemurl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bassem01URL',
        ),
        migrations.DeleteModel(
            name='Bassem02URL',
        ),
        migrations.DeleteModel(
            name='Bassem03URL',
        ),
        migrations.DeleteModel(
            name='BassemPerfectURL',
        ),
        migrations.DeleteModel(
            name='BassemUpURL',
        ),
    ]
