# Generated by Django 3.1.4 on 2021-01-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_outexam_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outexam',
            name='year',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=255, verbose_name='year'),
        ),
    ]
