# Generated by Django 3.1.4 on 2021-01-27 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210127_0210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OutExam',
            new_name='OuterExam',
        ),
    ]
