# Generated by Django 3.1.4 on 2021-01-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210127_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='outerexam',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outerexam',
            name='exam_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outerexam',
            name='minutes_of_exam',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outerexam',
            name='publisher',
            field=models.CharField(choices=[('EE', 'Mr. Ehab El Shafey'), ('GA', 'Herr Ali Rashed'), ('GM', 'Herr Mohammed Abdel Atty'), ('AH', 'Mohammed Abdel Halem'), ('GS', 'Herr Shady')], max_length=255, verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='outerexam',
            name='year',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=255, verbose_name='Academic Year'),
        ),
    ]
