# Generated by Django 3.1.4 on 2021-02-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_herrkhaledurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bassemurl',
            name='kind',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('up', 'up'), ('perfect', 'perfect'), ('innovate', 'innovate')], max_length=255, verbose_name='Kind'),
        ),
        migrations.AlterField(
            model_name='outerexam',
            name='publisher',
            field=models.CharField(choices=[('EE', 'Mr. Ehab El Shafey'), ('GA', 'Herr Ali Rashed'), ('GM', 'Herr Mohammed Abdel Atty'), ('AH', 'Mohammed Abdel Halem'), ('GS', 'Herr Shady'), ('GK', 'Herr Khaled Bakheet')], max_length=255, verbose_name='Publisher'),
        ),
    ]
