# Generated by Django 3.1.4 on 2021-02-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210202_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bassemyoutubeurl',
            name='link',
        ),
        migrations.AddField(
            model_name='bassemyoutubeurl',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bassemyoutubeurl',
            name='main_sort',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('النحو', 'النحو'), ('البلاغة', 'البلاغة'), ('المتحرر', 'المتحرر'), ('ارتق', 'ارتق'), ('دقيقتين', 'دقيقتين'), ('تكات', 'تكات'), ('تحفيزي', 'تحفيزي')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bassemyoutubeurl',
            name='sort2',
            field=models.CharField(blank=True, choices=[('النحو', 'النحو'), ('البلاغة', 'البلاغة'), ('المتحرر', 'المتحرر'), ('أدب', 'أدب'), ('منوعات', 'منوعات'), ('تحفيزي', 'تحفيزي'), ('دقيقتين', 'دقيقتين'), ('تكات', 'تكات'), ('ارتق', 'ارتق'), ('اعراب', 'اعراب'), ('دروس بلاغة', 'دروس بلاغة')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bassemyoutubeurl',
            name='video_id',
            field=models.CharField(default='النحو', max_length=512),
            preserve_default=False,
        ),
    ]
