# Generated by Django 3.1.4 on 2021-02-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210211_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bassemyoutubeurl',
            name='main_sort',
            field=models.CharField(choices=[('01', '1'), ('02', '2'), ('03', '3'), ('النحو', '04'), ('البلاغة', '05'), ('المتحرر', '06'), ('ارتق', '07'), ('دقيقتين', '08'), ('تكات', '09'), ('تحفيزي', '10')], max_length=255),
        ),
        migrations.AlterField(
            model_name='bassemyoutubeurl',
            name='sort2',
            field=models.CharField(blank=True, choices=[('النحو', '01'), ('البلاغة', '02'), ('المتحرر', '03'), ('أدب', '04'), ('منوعات', '05'), ('تحفيزي', '06'), ('دقيقتين', '07'), ('تكات', '08'), ('ارتق', '09'), ('اعراب', '10'), ('دروس بلاغة', '11')], max_length=255, null=True),
        ),
    ]
