# Generated by Django 3.1.4 on 2021-02-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210211_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bassemyoutubeurl',
            name='main_sort',
            field=models.CharField(choices=[('maintab1', '1'), ('maintab2', '2'), ('maintab3', '3'), ('maintab4', 'النحو'), ('maintab5', 'البلاغة'), ('maintab6', 'المتحرر'), ('maintab7', 'ارتق'), ('maintab8', 'دقيقتين'), ('maintab9', 'تكات'), ('maintab10', 'تحفيزي')], max_length=255),
        ),
        migrations.AlterField(
            model_name='bassemyoutubeurl',
            name='sort2',
            field=models.CharField(blank=True, choices=[('subtab1', 'النحو'), ('subtab2', 'البلاغة'), ('subtab3', 'المتحرر'), ('subtab4', 'أدب'), ('subtab5', 'منوعات'), ('subtab6', 'تحفيزي'), ('subtab7', 'دقيقتين'), ('subtab8', 'تكات'), ('subtab9', 'ارتق'), ('subtab10', 'اعراب'), ('subtab11', 'دروس بلاغة')], max_length=255, null=True),
        ),
    ]
