# Generated by Django 3.1.4 on 2021-03-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210303_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outerexam',
            name='publisher',
            field=models.CharField(choices=[('EE', 'Mr. Ehab El Shafey'), ('EG', 'Mr. Ehab Gaber'), ('GA', 'Herr Ali Rashed'), ('GM', 'Herr Mohammed Abdel Atty'), ('AH', 'Mohammed Abdel Halem'), ('GS', 'Herr Shady'), ('GK', 'Herr Khaled Bakheet')], max_length=255, verbose_name='Publisher'),
        ),
    ]
