# Generated by Django 3.1.4 on 2021-05-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210329_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outerexam',
            name='year',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('3Open', '3open')], max_length=255, verbose_name='Academic Year'),
        ),
    ]
