# Generated by Django 3.2.3 on 2021-06-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210502_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outerexam',
            name='publisher',
            field=models.CharField(choices=[('EE', 'Mr. Ehab El Shafey'), ('EA', 'Mr. Anis Fawzy'), ('EG', 'Mr. Ehab Gaber'), ('GA', 'Herr Ali Rashed'), ('GM', 'Herr Mohammed Abdel Atty'), ('AH', 'Mohammed Abdel Halem'), ('GS', 'Herr Shady'), ('GK', 'Herr Khaled Bakheet')], max_length=255, verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='outerexam',
            name='writer',
            field=models.CharField(choices=[('AMS', 'AMS'), ('AA', 'Ashraf'), ('HA', 'Hala'), ('MM', 'Maryam'), ('MG', 'Gouda'), ('A2', '2001')], max_length=255, verbose_name='Writer'),
        ),
    ]
