# Generated by Django 3.2.3 on 2021-05-22 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(choices=[('Arabic', 'Arabic'), ('Eng', 'Eng')], max_length=255)),
                ('address', models.CharField(max_length=512, verbose_name='Address')),
                ('slug', models.SlugField()),
                ('rating', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='NewTeacher')),
                ('years', models.ManyToManyField(to='reserve.Year')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('start_at', models.DateTimeField()),
                ('max_number', models.IntegerField()),
                ('is_privte', models.BooleanField(default=False)),
                ('girls_only', models.BooleanField(default=False)),
                ('semster', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=255)),
                ('is_online', models.BooleanField(default=False)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.teacher')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.year')),
            ],
            options={
                'verbose_name_plural': 'classes',
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('passcode', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=512, verbose_name='Address')),
                ('uuid', models.CharField(max_length=10)),
                ('phone_number', models.FloatField(verbose_name='Phone Number')),
                ('a_phone_number', models.FloatField(blank=True, null=True, verbose_name='Parent Phone Number')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255, verbose_name='Gender')),
                ('school_type', models.CharField(choices=[('أزهر', 'أزهر'), ('لغات', 'لغات'), ('عام', 'عام')], default='عام', max_length=255)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.class')),
            ],
        ),
    ]
