# Generated by Django 3.2.3 on 2021-05-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='email',
            field=models.EmailField(default='am6@am6.tech', max_length=254),
            preserve_default=False,
        ),
    ]
