# Generated by Django 3.2.3 on 2021-05-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_auto_20210522_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='a_phone_number',
            field=models.FloatField(default=1017747224, verbose_name='Parent Phone Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
