# Generated by Django 3.2.3 on 2021-09-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='month',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=2),
        ),
    ]
