# Generated by Django 3.1.4 on 2021-03-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='link',
            field=models.URLField(max_length=512),
        ),
    ]
