# Generated by Django 3.1.4 on 2021-03-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_auto_20210304_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='url',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
